---
version: '3.9'

services:
  cloudflare_tunnel:
    container_name: cloudflare_tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run

  gatus:
    image: twinproduction/gatus:stable
    container_name: gatus
    ports:
      - "8080:8080"
    volumes:
      - ./gatus_config:/config
      - ./gatus_data:/data/

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/JELLYFIN_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/tv:/data/tvshows
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/movies:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL=/ombi #optional
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/OMBI_CONFIG:/config
    ports:
      - 3579:3579
    restart: unless-stopped      

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/PROWLARR_CONFIG:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/RADARR_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/movies:/movies #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop # readarr doesn't release to latest tag
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/READARR_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/books:/books
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/SABNZBD_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/nzbd:/downloads #optional
      # - /path/to/incomplete/downloads:/incomplete-downloads #optional
    ports:
      - 8181:8181
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/SONARR_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/tv:/tv #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped