---
version: "2.1"
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL=/ombi #optional
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/OMBI_CONFIG:/config
    ports:
      - 3579:3579
    restart: unless-stopped