---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop # readarr doesn't release to latest tag
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/READARR_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/books:/books
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped