---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/SABNZBD_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/nzbd:/downloads #optional
      # - /path/to/incomplete/downloads:/incomplete-downloads #optional
    ports:
      - 8181:8181
    restart: unless-stopped