---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/MEDIA_DRIVE/MEDIA/SONARR_CONFIG:/config
      - /mnt/MEDIA_DRIVE/MEDIA/data/media/tv:/tv #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped