apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: prowlarr
    spec:
      containers:
        - env:
            - name: PUID
              value: "502"
            - name: PGID
              value: "20"
          image: lscr.io/linuxserver/prowlarr:develop
          name: prowlarrserver
          ports:
            - containerPort: 9696
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: prowlarr-config
      restartPolicy: Always
      volumes:
        - name: prowlarr-config
          hostPath:
            path: /MEDIA/PROWLARR_CONFIG
status: {}
